### ISSUE TITLE
EasyAdapter in Marshmallow 

### ISSUE THREAD

**Issue by MohammedHassouna** [ribot/easy-adapter#46]
When try to open app using EasyAdapter  in api 23 Marshmallow this bugs is show

` FATAL EXCEPTION: main
                                                                     Process: au.app, PID: 13866
                                                                     java.lang.RuntimeException: java.lang.IllegalAccessException: java.lang.Class<au.app.activity.DateDashBoardViewHolder> is not accessible from java.lang.Class<uk.co.ribot.easyadapter.EasyAdapterUtil>
                                                                         at uk.co.ribot.easyadapter.EasyAdapterUtil.createViewHolder(EasyAdapterUtil.java:18)
                                                                         at uk.co.ribot.easyadapter.BaseEasyRecyclerAdapter.onCreateViewHolder(BaseEasyRecyclerAdapter.java:76)
                                                                         at uk.co.ribot.easyadapter.BaseEasyRecyclerAdapter.onCreateViewHolder(BaseEasyRecyclerAdapter.java:34)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5228)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4453)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1732)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1732)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1732)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1497)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at android.widget.ScrollView.onLayout(ScrollView.java:1525)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                         at android.view.View.layout(View.java:16630)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5437)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                     	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495`

**Comment by ivacf** [comment]
It looks like EasyAdapter can't instantiate your `DateDashBoardViewHolder` for some reason. Make sure your view holder is a `public` class and if it's an inner class it needs to be `static`. Does it only happen on devices with api 23?

**Comment by MohammedHassouna** [comment]
in api 23 holder must be in public class 
thank you ^_^
